repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-azure-pipelines
      - id: check-jsonschema
        name: Validate job templates
        files: ^jobs/[^/]+$
        types: [yaml]
        args: ["--quiet", "--builtin-schema", "vendor.azure-pipelines"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.0
    hooks:
      - id: commitizen
