parameters:
  - name: cache
    type: boolean
    default: true
  - name: pythonVersion
    type: string
    default: "3.11"
    values:
      - "3.7"
      - "3.8"
      - "3.9"
      - "3.10"
      - "3.11"
  - name: sourcesRoot
    type: string
    default: "."
  - name: vmImage
    type: string
    default: "ubuntu-20.04"
    values:
      - "ubuntu-20.04"
      - "ubuntu-22.04"
      - "ubuntu-latest"

jobs:
  - job: black

    pool:
      vmImage: ${{ parameters.vmImage }}

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: ${{ parameters.pythonVersion }}
        displayName: Use Python ${{ parameters.pythonVersion }}
        name: PythonVersion

      - task: Cache@2
        condition: eq(${{ parameters.cache }}, true)
        inputs:
          key: py | "$(PythonVersion.pythonLocation)" | "black" | "${{ parameters.vmImage }}"
          path: $(PythonVersion.pythonLocation)
        displayName: Configure Python caching

      - script: |
          python -m pip install --upgrade pip
          python -m pip install \
            'black==21.9b0' \
            'click==7.1.2' \
            'mypy-extensions==1.0.0' \
            'pathspec==0.11.0' \
            'platformdirs==3.0.0' \
            'regex==2022.10.31' \
            'tomli==1.2.3' \
            'typed-ast==1.5.4' \
            'typing_extensions==4.5.0'
        displayName: Install dependencies

      - script: |
          black --check --diff --color ${{ parameters.sourcesRoot }}
        displayName: Return the status and output a diff for each file
