parameters:
  - name: cache
    type: boolean
    default: true
  - name: mypyRequirements
    type: string
    default: ""
  - name: pythonVersion
    type: string
    default: "3.11"
    values:
      - "2.7"
      - "3.6"
      - "3.7"
      - "3.8"
      - "3.9"
      - "3.10"
      - "3.11"
  - name: sourcesRoot
    type: string
    default: "."
  - name: vmImage
    type: string
    default: "ubuntu-20.04"
    values:
      - "ubuntu-20.04"
      - "ubuntu-22.04"
      - "ubuntu-latest"

jobs:
  - job: mypy

    pool:
      vmImage: ${{ parameters.vmImage }}

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: ${{ parameters.pythonVersion }}
        displayName: Use Python ${{ parameters.pythonVersion }}
        name: PythonVersion

      - task: Cache@2
        condition: eq(${{ parameters.cache }}, true)
        inputs:
          key: py | "$(PythonVersion.pythonLocation)" | "mypy" | "${{ parameters.vmImage }}"
          path: $(PythonVersion.pythonLocation)
        displayName: Configure Python caching

      - script: |
          python -m pip install --upgrade pip
          python -m pip install \
            'mypy==0.971' \
            'mypy-extensions==1.0.0' \
            'tomli==2.0.1' \
            'typed-ast==1.5.4' \
            'typing_extensions==4.5.0'
        displayName: Install dependencies

      - script: |
          python -m pip install --requirement ${{ parameters.mypyRequirements }}
        condition: ne(${{ parameters.mypyRequirements }}, '')

      - script: |
          mypy ${{ parameters.sourcesRoot }}
        displayName: Run type check on code base
